### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mte90** [blacktrub/cli-stream-chat#1]
I got this with youtube live recording and a twitch channel. I wanted try the tool to see if worked but seems that works only with live stuff so I cannot test it.
```
panic: runtime error: index out of range [0] with length 0

goroutine 7 [running]:
github.com/abhinavxd/youtube-live-chat-downloader/v2.ParseInitialData({_, _})
        /home/mte90/go/pkg/mod/github.com/abhinavxd/youtube-live-chat-downloader/v2@v2.0.1/yt_chat.go:259 +0x446
main.listenYoutube({{}, {0x0, 0x0, 0x2}}, {0x7ffdc3b222b3, 0x2b}, {0xc000072300, 0x4, 0x4})
        /home/mte90/Desktop/kde/cli-stream-chat/chat.go:25 +0x78
created by main.runListeners
        /home/mte90/Desktop/kde/cli-stream-chat/chat.go:68 +0x1c8
exit status 2
```

**Comment by blacktrub** [comment]
@Mte90 hello! You can check it only with Twitch (you can be offline on twitch) if you want, for example
```
go run chat.go --twitch blacktrub_
```

I'm not sure if app works properly with offline Youtube, but with online it works fine.

**Comment by Mte90** [comment]
Yes it isn't a problem I was trying to see if works.
I wasn't expecting a crash but like a message.

Do you think that is possible to get the link automatically from the youtube live?

**Comment by blacktrub** [comment]
@Mte90 I think it's possible and I'm interested in that feature too, so I'll try to add it.

**Comment by Mte90** [comment]
Hi I tried with a live streaming on youtube and I am getting the same error:
```
panic: runtime error: index out of range [0] with length 0

goroutine 8 [running]:
github.com/abhinavxd/youtube-live-chat-downloader/v2.ParseInitialData({_, _})
        /home/mte90/go/pkg/mod/github.com/abhinavxd/youtube-live-chat-downloader/v2@v2.0.1/yt_chat.go:259 +0x446
cli-stream-chat/pkg/provider.(*Youtube).Listen(0x8eb868, 0xc0000163e0, {0x7ffd0c49f6e2, 0x2b}, {0xc000070300, 0x3, 0x4}, 0xc000024180)
        /home/mte90/Desktop/kde/cli-stream-chat/pkg/provider/youtube.go:15 +0x66
created by main.runListeners
        /home/mte90/Desktop/kde/cli-stream-chat/chat.go:26 +0x21a
exit status 2
```

**Comment by Mte90** [comment]
Looking at the code is a bug of the dependence not of this tool
