### ISSUE TITLE
fix panic 

### ISSUE THREAD

**Issue by blacktrub** [blacktrub/cli-stream-chat#23]
```
fatal error: concurrent map iteration and map write

goroutine 360 [running]:
cli-stream-chat/internal/color.(*MakePretty).getColor(...)
	/home/bt/go/src/cli-stream-chat/internal/color/pretty.go:35
cli-stream-chat/internal/color.(*MakePretty).Colorize(0xc000066d60, 0x6881db2, {0xc0001145bb, 0x7})
	/home/bt/go/src/cli-stream-chat/internal/color/pretty.go:20 +0x87
cli-stream-chat/internal/msg.(*Message).PrettyText(0xc000151f18)
	/home/bt/go/src/cli-stream-chat/internal/msg/msg.go:76 +0xa3
cli-stream-chat/internal/pipe.(*Stdout).Write(0xc0004887cf?, {0x6881db2, {0xc0001145bb, 0x7}, {0xc0001146bd, 0x8}, {0x6f1468, 0x2}, 0xc000566120, {0xc000114628, ...}, ...})
	/home/bt/go/src/cli-stream-chat/internal/pipe/stdout.go:11 +0x1e
cli-stream-chat/internal/provider.(*Stream).Run.func2.1({0x769ee0?, 0x941bf0?})
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:57 +0x79
created by cli-stream-chat/internal/provider.(*Stream).Run.func2
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:56 +0xf1

goroutine 1 [chan receive, 50 minutes]:
cli-stream-chat/internal/provider.(*Stream).Run(0xc00010acc0, {0x76c568?, 0xc000020118})
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:66 +0x230
main.main()
	/home/bt/go/src/cli-stream-chat/cmd/main.go:53 +0xafe

goroutine 6 [select]:
github.com/gempir/go-twitch-irc/v3.(*Client).startParser(0xc0001401a0)
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:918 +0x9c
github.com/gempir/go-twitch-irc/v3.(*Client).makeConnection(0xc0001401a0, 0x10?, 0xc00010cea0?)
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:760 +0x2c7
github.com/gempir/go-twitch-irc/v3.(*Client).Connect(0xc0001401a0)
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:710 +0x15f
cli-stream-chat/internal/provider.(*Twitch).Listen(0xc00010adb0, {0x0?, 0x0?}, 0xc000100120)
	/home/bt/go/src/cli-stream-chat/internal/provider/twitch.go:51 +0xd2
cli-stream-chat/internal/provider.(*Stream).Run.func1({0x769f00?, 0xc00010adb0?})
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:45 +0x3f
created by cli-stream-chat/internal/provider.(*Stream).Run
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:44 +0x77

goroutine 7 [chan receive]:
cli-stream-chat/internal/provider.(*Stream).Run.func2()
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:54 +0x7d
created by cli-stream-chat/internal/provider.(*Stream).Run
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:51 +0x21b

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x7f8608ea9038, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00014e080?, 0xc0000c6000?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00014e080, {0xc0000c6000, 0x1800, 0x1800})
	/usr/lib/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc00014e080, {0xc0000c6000?, 0xc0000c600d?, 0x400000?})
	/usr/lib/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00009a000, {0xc0000c6000?, 0x0?, 0xc0000617c0?})
	/usr/lib/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000254030, {0xc0000c6000?, 0xc000254030?, 0x0?})
	/usr/lib/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc00009e290, {0x769fa0, 0xc000254030})
	/usr/lib/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00009e000, {0x76a460?, 0xc00009a000}, 0x1800?)
	/usr/lib/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00009e000, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc00009e000, {0xc000218000, 0x1000, 0x40ec47?})
	/usr/lib/go/src/crypto/tls/conn.go:1316 +0x16f
bufio.(*Reader).fill(0xc000061f40)
	/usr/lib/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).ReadSlice(0xc000061f40, 0x38?)
	/usr/lib/go/src/bufio/bufio.go:372 +0x2f
bufio.(*Reader).ReadLine(0xc000061f40)
	/usr/lib/go/src/bufio/bufio.go:401 +0x27
net/textproto.(*Reader).readLineSlice(0xc000061ec0)
	/usr/lib/go/src/net/textproto/reader.go:56 +0x99
net/textproto.(*Reader).ReadLine(...)
	/usr/lib/go/src/net/textproto/reader.go:39
github.com/gempir/go-twitch-irc/v3.(*Client).startReader(0xc0001401a0, {0x7f8608309a18?, 0xc00009e000?}, 0x0?)
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:813 +0x1fa
created by github.com/gempir/go-twitch-irc/v3.(*Client).makeConnection
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:740 +0x1ac

goroutine 37 [select]:
github.com/gempir/go-twitch-irc/v3.(*Client).startPinger.func1()
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:840 +0x145
created by github.com/gempir/go-twitch-irc/v3.(*Client).startPinger
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:834 +0xee

goroutine 38 [select, 2 minutes]:
github.com/gempir/go-twitch-irc/v3.(*Client).startWriter(0xc0001401a0, {0x7f8608309a90, 0xc00009e000}, 0x0?)
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:888 +0x117
created by github.com/gempir/go-twitch-irc/v3.(*Client).makeConnection
	/home/bt/go/pkg/mod/github.com/gempir/go-twitch-irc/v3@v3.0.0/client.go:755 +0x2ba

goroutine 370 [IO wait]:
internal/poll.runtime_pollWait(0x7f8608ea8f48, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0000a2100?, 0xc00016a000?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000a2100, {0xc00016a000, 0xd80, 0xd80})
	/usr/lib/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc0000a2100, {0xc00016a000?, 0xc00016a2a8?, 0x1a?})
	/usr/lib/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00009a098, {0xc00016a000?, 0x5bdce3?, 0xc0000188b0?})
	/usr/lib/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0000120f0, {0xc00016a000?, 0xc0000120f0?, 0x0?})
	/usr/lib/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc000018990, {0x769fa0, 0xc0000120f0})
	/usr/lib/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000018700, {0x76a460?, 0xc00009a098}, 0xadd?)
	/usr/lib/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000018700, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc000018700, {0xc0002f3000, 0x1000, 0x61c8a0?})
	/usr/lib/go/src/crypto/tls/conn.go:1316 +0x16f
bufio.(*Reader).Read(0xc000166b40, {0xc0001dc2e0, 0x9, 0x62a3a5?})
	/usr/lib/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x769de0, 0xc000166b40}, {0xc0001dc2e0, 0x9, 0x9}, 0x9)
	/usr/lib/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/lib/go/src/io/io.go:351
net/http.http2readFrameHeader({0xc0001dc2e0?, 0x9?, 0xc00010aff0?}, {0x769de0?, 0xc000166b40?})
	/usr/lib/go/src/net/http/h2_bundle.go:1567 +0x6e
net/http.(*http2Framer).ReadFrame(0xc0001dc2a0)
	/usr/lib/go/src/net/http/h2_bundle.go:1831 +0x95
net/http.(*http2clientConnReadLoop).run(0xc000524f98)
	/usr/lib/go/src/net/http/h2_bundle.go:9187 +0x12e
net/http.(*http2ClientConn).readLoop(0xc00009c480)
	/usr/lib/go/src/net/http/h2_bundle.go:9082 +0x6f
created by net/http.(*http2Transport).newClientConn
	/usr/lib/go/src/net/http/h2_bundle.go:7779 +0xc3c

goroutine 362 [runnable]:
runtime.goexit1()
	/usr/lib/go/src/runtime/proc.go:3616 +0x54
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1599 +0x6
created by cli-stream-chat/internal/provider.(*Stream).Run.func2
	/home/bt/go/src/cli-stream-chat/internal/provider/provider.go:56 +0xf1

goroutine 388 [IO wait]:
internal/poll.runtime_pollWait(0x7f8608ea8e58, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00021a180?, 0xc00045e000?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00021a180, {0xc00045e000, 0x1980, 0x1980})
	/usr/lib/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc00021a180, {0xc00045e000?, 0xc00045e005?, 0x470?})
	/usr/lib/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00040c008, {0xc00045e000?, 0x427f00?, 0xc00043c1b0?})
	/usr/lib/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0002005b8, {0xc00045e000?, 0xc0002005b8?, 0x0?})
	/usr/lib/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc00043c290, {0x769fa0, 0xc0002005b8})
	/usr/lib/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00043c000, {0x76a460?, 0xc00040c008}, 0x294a5?)
	/usr/lib/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00043c000, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
```

**Comment by blacktrub** [comment]
solved
